name: Remove Backend Dev

on:
  pull_request:
    types: [closed]

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

env:
  # PR number
  VERSION: pr-$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency: ci-${{ github.ref }}

    steps:
      - uses: actions/checkout@e2f20e631ae6d7dd3b768f56a5d2af784dd54791 # tag=v2
      - name: 'Removing backend stage: ${{ env.VERSION }}'
        uses: './.github/actions/sls-remove'
        with:
          stage: ${{ env.VERSION }}
          aws-account-id: ${{ secrets.DEV_AWS_ACCOUNT_ID }}