name: Remove Backend Dev

on:
  pull_request:
    types: [closed]

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

jobs:
  remove:
    runs-on: ubuntu-latest
    concurrency: ci-${{ github.ref }}

    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3
      - name: 'Removing backend stage: ${{ env.VERSION }}'
        uses: './.github/actions/sls-remove'
        with:
          stage: pr-${{ github.event.number }}
          aws-account-id: ${{ secrets.DEV_AWS_ACCOUNT_ID }}