name: Deploy Backend Dev

on:
  pull_request:

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

env:
  # PR number
  VERSION: pr-$(echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }')
  REGION: us-east-1

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3
      - name: Install Dependencies
        run: npm i
      - name: Unit Tests
        run: npm run test:unit

  deploy:
    runs-on: ubuntu-latest
    concurrency: ci-${{ github.ref }}

    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3
      - name: 'Deploying backend'
        uses: './.github/actions/sls-deploy'
        with:
          stage: ${{ env.VERSION }}
          aws-account-id: ${{ secrets.DEV_AWS_ACCOUNT_ID }}
          aws-region: ${{ env.REGION }}
  e2e-tests:
    needs: deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3
      - name: 'Get service info'
        uses: './.github/actions/sls-info'
        id: service-info
        with:
          stage: ${{ env.VERSION }}
          aws-account-id: ${{ secrets.DEV_AWS_ACCOUNT_ID }}
          aws-region: ${{ env.REGION }}
      - name: Install Dependencies
        run: npm i
      - name: Run E2E Tests
        run: BASE_URL=${{ steps.service-info.outputs.URL }} npm run test:e2e

