name: Deploy Backend Dev

on:
  pull_request:

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

env:
  # PR number
  VERSION: pr-${{ github.event.number }}

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3
      - name: Install Dependencies
        run: npm i
      - name: Unit Tests
        run: npm run test:unit

  deploy:
    runs-on: ubuntu-latest
    concurrency: ci-${{ github.ref }}

    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3
      - name: 'Deploying backend to stage: ${{ env.VERSION }}'
        uses: './.github/actions/sls-deploy'
        with:
          stage: ${{ env.VERSION }}
          aws-account-id: ${{ secrets.DEV_AWS_ACCOUNT_ID }}
          aws-region: ${{ env.REGION }}
      - name: Debug
        run: cat .env
      - name: Run E2E Tests
        run: npm run test:e2e

