name: Deploy Backend Dev

on:
  pull_request:

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

env:
  # PR number
  VERSION: pr-$(echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }')
  REGION: us-east-1

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3
      - name: Install Dependencies
        run: npm i
      - name: Unit Tests
        run: npm run test:unit

  deploy:
    runs-on: ubuntu-latest
    concurrency: ci-${{ github.ref }}

    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3
      - name: 'Deploying backend to stage: ${{ env.VERSION }}'
        uses: './.github/actions/sls-deploy'
        with:
          stage: ${{ env.VERSION }}
          aws-account-id: ${{ secrets.DEV_AWS_ACCOUNT_ID }}
          aws-region: ${{ env.REGION }}
  e2e-test:
    needs: deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3
      - name: Install Dependencies
        run: npm i
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@67fbcbb121271f7775d2e7715933280b06314838 # tag=v1
        with:
          role-to-assume: arn:aws:iam::${{ secrets.DEV_AWS_ACCOUNT_ID }}:role/trade-game-backend-DeployerRole
          role-session-name: gha_deployer
          aws-region: ${{ env.REGION }}
      - name: Get Service Info
        run: npm run info -- --stage ${{ env.VERSION }} --region ${{ env.REGION }} > deploy.info || cat deploy.info
      - name: Get Service Endpoint
        id: url
        run: "grep -o 'ServiceEndpoint.*' deploy.info | sed 's/ServiceEndpoint: /URL=/' >> $GITHUB_OUTPUT"
      - run: BASE_URL=${{ steps.url.outputs.URL }} npm run test:e2e

