name: Deploy Backend Main

on:
  push:
    branches:
      - main

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

env:
  VERSION: 20221023

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency: main

    steps:
      - uses: actions/checkout@7dd9e2a3dc350cf687eb1b2a4fadfee8c8e49675 # v3
      - name: 'Deploying backend to stage: ${{ env.VERSION }}'
        uses: './.github/actions/sls-deploy'
        with:
          stage: ${{ env.VERSION }}
          aws-account-id: ${{ secrets.PROD_AWS_ACCOUNT_ID }}