name: Deploy Backend Main

on:
  push:
    branches:
      - main

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

env:
  VERSION: 20221023
  REGION: us-east-1

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3
      - name: Install Dependencies
        run: npm i
      - name: Unit Tests
        run: npm run test:unit

  deploy:
    runs-on: ubuntu-latest
    concurrency: main

    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3
      - name: 'Deploying backend to stage: ${{ env.VERSION }}'
        uses: './.github/actions/sls-deploy'
        id: deploy
        with:
          stage: ${{ env.VERSION }}
          aws-account-id: ${{ secrets.PROD_AWS_ACCOUNT_ID }}

  e2e-tests:
    runs-on: ubuntu-latest
    concurrency: main
    needs: [deploy]
    steps:
      - name: Configure AWS Credentials for Test
        uses: aws-actions/configure-aws-credentials@67fbcbb121271f7775d2e7715933280b06314838 # tag=v1
        with:
          role-to-assume: arn:aws:iam::${{ secrets.PROD_AWS_ACCOUNT_ID }}:role/trade-game-backend-${{ env.VERSION }}-TestUserRole
          role-session-name: test_user
          aws-region: ${{ env.REGION }}
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3
      - name: Install Dependencies
        run: npm i
      - name: Get Service Info
        run: npm run export-env -- --stage ${{ env.VERSION }} --region ${{ env.REGION }} --all
      - name: Run E2E Tests
        run: npm run test:e2e